-- General Querys
-- Create Table TARGET_MYSQLLOCATION on the Oracle server.
-- Such table relies on hr.location from the MYSQL server

CREATE TABLE TARGET_MYSQLLOCATION
(
LocationID NUMBER(10),
Name varchar2(50) NOT NULL,
CostRate NUMBER(35) NOT NULL,
Availability NUMBER(8,2) NOT NULL,
ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);


---  CREATE TABLE: COMPOUND JOB
-- JOBS AND JOB_HISTORY

select dbms_metadata.get_ddl('TABLE', table_name) from user_tables;

-- CREATE AS FIRST TABLE
-- ALTER TABLE AND ADD THE LAST COLUMN FROM JOB_HISTORY

CREATE TABLE TARGET_COMPOUNDJOB AS SELECT * FROM JOBS WHERE 1=0;

ALTER TABLE TARGET_COMPOUNDJOB ADD(
"DEPARTMENT_ID" NUMBER(4,0)
);


-- TEMP

select * from TARGET_MYSQLLOCATION;

select COUNT(*) from TARGET_MYSQLLOCATION;

---  CREATE TABLE: COMPOUND JOB
-- JOBS AND JOB_HISTORY

select dbms_metadata.get_ddl('TABLE', table_name) from user_tables;

-- CREATE AS FIRST TABLE
-- ALTER TABLE AND ADD THE LAST COLUMN FROM JOB_HISTORY

CREATE TABLE TARGET_COMPOUNDJOB AS SELECT * FROM JOBS WHERE 1=0;

ALTER TABLE TARGET_COMPOUNDJOB ADD(
"DEPARTMENT_ID" NUMBER(4,0)
);

SELECT COUNT(*) FROM TARGET_COMPOUNDJOB

SELECT * FROM TARGET_COMPOUNDJOB

SELECT * FROM JOBS ORDER BY JOB_ID

SELECT * FROM JOB_HISTORY ORDER BY JOB_ID